# Generated by Django 2.1.2 on 2018-10-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_id', models.IntegerField(db_index=True, verbose_name='条码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('genre', models.CharField(max_length=200, verbose_name='类别')),
                ('buy_price', models.IntegerField(verbose_name='进货价')),
                ('sale_price', models.IntegerField(verbose_name='销售价')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='供货商')),
            ],
        ),
    ]
