# Generated by Django 2.1.2 on 2018-11-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_id', models.CharField(max_length=30, unique=True, verbose_name='条码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('genre', models.CharField(max_length=100, verbose_name='类别')),
                ('buy_price', models.FloatField(verbose_name='进货价')),
                ('sale_price', models.FloatField(verbose_name='销售价')),
                ('quantify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_goods', to='common.Quantify', verbose_name='单位')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_shops', to='common.Supplier', verbose_name='供货商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'shop_good',
                'ordering': ['-id'],
            },
        ),
    ]
