# Generated by Django 2.1.2 on 2018-12-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinestockrecord',
            name='examine_person',
            field=models.CharField(default='-', max_length=30, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='examinestockrecord',
            name='examine_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核日期'),
        ),
        migrations.AlterField(
            model_name='examinestockrecord',
            name='stock_genre',
            field=models.IntegerField(choices=[(1, '入库'), (-1, '出库')], default=1, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='examinestockrecord',
            name='stock_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出/入库日期'),
        ),
    ]
