# Generated by Django 2.1.2 on 2018-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181026_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='bar_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='条码'),
        ),
    ]
