# Generated by Django 2.1.2 on 2018-12-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_examinestockrecord_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinestockrecord',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='examinestockrecord',
            name='shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='shop.Shop', verbose_name='所属门店'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Shop', verbose_name='所属门店'),
        ),
    ]
