# Generated by Django 2.1.2 on 2018-12-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181216_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrecord',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
