# Generated by Django 2.1.2 on 2018-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181216_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinestockrecord',
            name='examine_status',
            field=models.IntegerField(choices=[(-1, '待审核'), (0, '未通过'), (1, '已通过')], default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='examinestockrecord',
            name='stock_genre',
            field=models.IntegerField(choices=[(1, '入库'), (2, '出库')], default=1, verbose_name='操作类型'),
        ),
    ]
