# Generated by Django 2.1.2 on 2018-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181217_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstock',
            name='stock_sale_price',
            field=models.FloatField(blank=True, null=True, verbose_name='门店售价'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='buy_price',
            field=models.FloatField(verbose_name='单价'),
        ),
    ]
