# Generated by Django 2.1.2 on 2018-12-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181217_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinestockrecord',
            name='examine_status',
            field=models.IntegerField(choices=[(-1, '待审核'), (0, '未通过'), (1, '已通过')], default=-1, verbose_name='审核状态'),
        ),
    ]
