# Generated by Django 2.1.2 on 2018-12-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181217_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='stock_genre',
            field=models.IntegerField(choices=[(1, '入库'), (2, '出库')], default=1, verbose_name='操作类型'),
        ),
    ]
