# Generated by Django 2.1.2 on 2018-12-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181218_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinestockrecord',
            name='total_price',
            field=models.FloatField(default=50, verbose_name='总金额'),
            preserve_default=False,
        ),
    ]
