# Generated by Django 2.1.2 on 2019-01-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20181224_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodpackage',
            old_name='number',
            new_name='package_number',
        ),
    ]
