# Generated by Django 2.1.2 on 2018-10-24 04:26

import Utils.my_validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_id', models.IntegerField(db_index=True, verbose_name='条码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('genre', models.CharField(max_length=200, verbose_name='类别')),
                ('buy_price', models.IntegerField(verbose_name='进货价')),
                ('sale_price', models.IntegerField(verbose_name='销售价')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='供货商')),
            ],
        ),
        migrations.CreateModel(
            name='XYUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='姓')),
                ('last_name', models.CharField(max_length=30, verbose_name='名')),
                ('sex', models.CharField(choices=[('boy', '男'), ('girl', '女')], default='boy', max_length=10, verbose_name='性别')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='邮箱地址')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='手机号码')),
                ('id_number', models.CharField(help_text='请输入18位有效身份证号码', max_length=80, validators=[Utils.my_validators.UserIDCardValidator()], verbose_name='身份证号')),
                ('avatar', models.ImageField(blank=True, height_field=12, null=True, upload_to='driver/%Y/%m/%d', verbose_name='头像', width_field=12)),
                ('position', models.CharField(choices=[('boss', '老板'), ('manager', '管理员'), ('cashier', '收银员'), ('waiter', '服务员'), ('pullover', '送货员')], default='cashier', max_length=30, verbose_name='职位')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=True, related_name='xu_user', to=settings.AUTH_USER_MODEL, verbose_name='鑫意客户')),
            ],
            options={
                'verbose_name': '鑫意用户',
                'verbose_name_plural': '用户',
                'ordering': ['-id'],
                'permissions': (('boos', '老板'), ('manager', '管理员'), ('cashier', '收银员'), ('staff', '普通员工'), ('goods_manage', '商品管理'), ('sale_manage', '销售管理'), ('order_goods_manage', '进货管理'), ('stock_manage', '库存管理'), ('report_manage', '报表管理'), ('setting_manage', '设置管理')),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
