# Generated by Django 2.1.2 on 2018-10-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xyuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='xyuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='xyuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='xyuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='xyuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='xyuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='xyuser',
            name='username',
        ),
    ]
