# Generated by Django 2.1.2 on 2018-12-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('shop', '0001_initial'),
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xyuser',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_employee', to='shop.Shop', verbose_name='所属门店'),
        ),
        migrations.AddField(
            model_name='xyuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
