# Generated by Django 2.1.2 on 2018-10-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20181024_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xyuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='driver/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
