# Generated by Django 2.1.2 on 2018-12-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20181212_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xyuser',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='set_employee', to='shop.Shop', verbose_name='所属门店'),
        ),
    ]
