# Generated by Django 2.1.2 on 2018-10-17 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20181017_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xyuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=True, related_name='xu_user', to=settings.AUTH_USER_MODEL, verbose_name='鑫客户'),
        ),
    ]
