# Generated by Django 2.1.2 on 2018-10-17 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20181017_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xyuser',
            options={'ordering': ['-id'], 'permissions': (('boos', '老板'), ('manager', '管理员'), ('cashier', '收银员'), ('staff', '普通员工'), ('goods_manage', '商品管理'), ('sale_manage', '销售管理'), ('order_goods_manage', '进货管理'), ('stock_manage', '库存管理'), ('report_manage', '报表管理'), ('setting_manage', '设置管理')), 'verbose_name': '鑫用户', 'verbose_name_plural': '鑫用户'},
        ),
        migrations.AlterField(
            model_name='xyuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=True, related_name='xu_user', to=settings.AUTH_USER_MODEL, verbose_name='鑫意客户'),
        ),
    ]
