# Generated by Django 2.1.2 on 2019-01-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20181213_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xyuser',
            options={'ordering': ['-id'], 'permissions': (('boss', '老板'), ('manager', '管理员'), ('cashier', '收银员'), ('staff', '普通员工'), ('goods_manage', '商品管理'), ('sale_manage', '销售管理'), ('order_goods_manage', '进货管理'), ('stock_manage', '库存管理'), ('report_manage', '报表管理'), ('setting_manage', '设置管理')), 'verbose_name': '鑫意用户', 'verbose_name_plural': '用户'},
        ),
    ]
