# Generated by Django 2.1.2 on 2019-01-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0014_auto_20190110_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodOperateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, verbose_name='流水号')),
                ('bar_id', models.CharField(max_length=30, verbose_name='条码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('quantify', models.CharField(blank=True, max_length=30, null=True, verbose_name='单位')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('package_number', models.IntegerField(verbose_name='包装数量')),
                ('sale_price', models.FloatField(verbose_name='售价')),
                ('profit', models.FloatField(verbose_name='毛利润')),
                ('discount_profit', models.FloatField(verbose_name='毛利率')),
                ('operate_type', models.CharField(choices=[('sale', '出售'), ('return', '退货'), ('damage', '报损')], default=1, max_length=20, verbose_name='操作类型')),
                ('sale_status', models.CharField(choices=[('finish', '完成'), ('return', '退订')], default=1, max_length=20, verbose_name='订单状态')),
                ('operator', models.CharField(max_length=30, verbose_name='操作人')),
                ('shop_name', models.CharField(max_length=100, verbose_name='所属门店')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Good', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品运营记录',
                'verbose_name_plural': '商品运营记录',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, verbose_name='流水号')),
                ('operate_type', models.CharField(choices=[('sale', '出售'), ('return', '退货'), ('damage', '报损')], default=1, max_length=20, verbose_name='操作类型')),
                ('sale_status', models.CharField(choices=[('finish', '完成'), ('return', '退订'), ('credit', '挂单')], default=1, max_length=20, verbose_name='订单状态')),
                ('number', models.IntegerField(verbose_name='商品个数')),
                ('sale_price', models.FloatField(verbose_name='预期售价')),
                ('discount_price', models.FloatField(verbose_name='实际售价')),
                ('discount', models.FloatField(verbose_name='折扣')),
                ('profit', models.FloatField(verbose_name='毛利润')),
                ('discount_profit', models.FloatField(verbose_name='毛利率')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '运营订单',
                'verbose_name_plural': '运营订单',
                'ordering': ['-id'],
            },
        ),
    ]
