# Generated by Django 2.1.2 on 2019-01-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodoperaterecord',
            name='stock_buy_price',
            field=models.FloatField(default=1, verbose_name='成本价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodorder',
            name='discount_price',
            field=models.FloatField(verbose_name='实际售价总额'),
        ),
        migrations.AlterField(
            model_name='goodorder',
            name='sale_price',
            field=models.FloatField(verbose_name='预期售价总额'),
        ),
    ]
