# Generated by Django 2.1.2 on 2019-01-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190110_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodorder',
            name='buy_price_total',
            field=models.FloatField(default=12, verbose_name='成本总额'),
            preserve_default=False,
        ),
    ]
