# Generated by Django 2.1.2 on 2019-01-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_goodorder_buy_price_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodorder',
            old_name='sale_price',
            new_name='pre_sale_price',
        ),
        migrations.AlterField(
            model_name='goodoperaterecord',
            name='operate_type',
            field=models.CharField(choices=[('sale', '出售'), ('return', '退货'), ('damage', '报损')], default='sale', max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='goodoperaterecord',
            name='sale_status',
            field=models.CharField(choices=[('finish', '完成'), ('return', '退订')], default='finish', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='goodorder',
            name='operate_type',
            field=models.CharField(choices=[('sale', '出售'), ('return', '退货'), ('damage', '报损')], default='sale', max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='goodorder',
            name='sale_status',
            field=models.CharField(choices=[('finish', '完成'), ('return', '退订'), ('credit', '挂单')], default='finish', max_length=20, verbose_name='订单状态'),
        ),
    ]
