# Generated by Django 2.1.2 on 2019-01-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190110_2000'),
        ('sale', '0004_auto_20190113_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodoperaterecord',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='goodoperaterecord',
            name='shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='shop.Shop', verbose_name='所属门店'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodorder',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.Shop', verbose_name='所属门店'),
            preserve_default=False,
        ),
    ]
