# Generated by Django 2.1.2 on 2019-01-16 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20190113_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodoperaterecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_goods_sale', to=settings.AUTH_USER_MODEL, verbose_name='销售人'),
        ),
        migrations.AlterField(
            model_name='goodorder',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_orders', to=settings.AUTH_USER_MODEL, verbose_name='订单操作人'),
        ),
    ]
